[default]
packages = [
  "python3",
  "gcc",
  "libmysqlclient-dev",      # Inclui as bibliotecas de desenvolvimento do MySQL
  "build-essential",         # Ferramentas essenciais para compilar pacotes
  "libmariadb-dev",          # Alternativa ao MySQL
  "libmariadb-dev-compat",   # Pacotes de compatibilidade para MariaDB
  "pkg-config"               # Ferramenta que ajuda na localização de pacotes
]

[variables]
MYSQLCLIENT_CFLAGS = "-I/usr/include/mariadb"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmariadb"