# Generated by Django 5.1 on 2024-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ja_votou',
            field=models.BooleanField(default=False),
        ),
    ]
