# Generated by Django 5.1 on 2024-10-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pessoa_ja_votou'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='sobrenome',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
